### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by n3on4s** [WyriHaximus/MinifyHtml#8]
Hi there, 

Is there a hope for this Deprecation  fix? :)  
`Notice: Deprecated (16384): Response::type() is deprecated. Use getType() or withType() instead. - /vendor/wyrihaximus/minify-html/src/View/Helper/MinifyHtmlHelper.php, line: 37`

**Comment by WyriHaximus** [comment]
Doh sorry, will do this tonight

**Comment by WyriHaximus** [comment]
@n3on4s just filed #9, could you try it out with `composer require wyrihaximus/minify-html:dev-fix-deprecation-warnings`?

**Comment by n3on4s** [comment]
Hi, sorry for delay. There is a tinny issue.
```
2019-02-27 15:10:52 Error: [Error] Call to undefined method App\View\AppView::getResponse()
Request URL: /zzz
Referer URL: http://localhost/xxx/zzz
Stack Trace:
#0 C:\wamp64\www\xxx\vendor\cakephp\cakephp\src\Event\EventManager.php(353): WyriHaximus\MinifyHtml\View\Helper\MinifyHtmlHelper->afterLayout(Object(Cake\Event\Event), 'C:\\wamp64\\www\\x...')
#1 C:\wamp64\www\xxx\vendor\cakephp\cakephp\src\Event\EventManager.php(330): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#2 C:\wamp64\www\xxx\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(114): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#3 C:\wamp64\www\xxx\vendor\cakephp\cakephp\src\View\View.php(852): Cake\View\View->dispatchEvent('View.afterLayou...', Array)```

```
This modify works.
```php
public function afterLayout()
    {
        if (
            (
                !Configure::read('debug') ||
                Configure::read('WyriHaximus.MinifyHtml.debugOverride')
            ) &&
            in_array($this->_View->response->getType(), $this->mimeTypes) //I gues only property of response is accessible instead of getResponse()
        ) {
            $content = $this->_View->fetch('content');
            $content = \WyriHaximus\MinifyHtml\compress($content);
            $this->_View->assign('content', $content);
        }
    }
```

**Comment by WyriHaximus** [comment]
Ah doh the getRequest is since 3.7, updating to CakePHP 3.7 should fix that error. Also updated the PR with the CakePHP 3.7 requirement

**Comment by WyriHaximus** [comment]
[`1.2.0`](https://github.com/WyriHaximus/MinifyHtml/releases/tag/1.2.0) with the fix for this
